name: Validate & publish container project

on:
  push:
    branches: [ main ] # edge
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ] # versioned

jobs:
  container-validate:
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@47e334e5d1ebfef7be26a89673feb33c50c6baac

  container-pre-publish:
    needs: container-validate
    runs-on: ubuntu-latest
    outputs:
      acme-sh-version: ${{ steps.acme-sh-version.outputs.ACME_SH_VERSION }}
      container-image-name: ${{ steps.container-image-name.outputs.CONTAINER_IMAGE_NAME }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Find out acme.sh version
        id: acme-sh-version
        run: echo "ACME_SH_VERSION=$(scripts/acme-sh-version.sh src)" >> $GITHUB_OUTPUT

      - name: Compose container repositories image name
        id: container-image-name
        run: echo "CONTAINER_IMAGE_NAME=${GH_REPO_NAME#container-}" >> $GITHUB_OUTPUT
        env:
          GH_REPO_NAME: ${{ github.event.repository.name }}


  container-publish:
    needs: [container-validate, container-pre-publish]
    permissions:
      packages: write
      id-token: write # used to complete the identity challenge with sigstore/fulcio
    uses: anthochamp/dev-toolbox/.github/workflows/container-publish.yml@47e334e5d1ebfef7be26a89673feb33c50c6baac
    with:
      build-context: src
      additional-tags: |
        type=edge
        type=semver,pattern={{version}}+acmesh${{ needs.container-pre-publish.outputs.acme-sh-version }}
        type=semver,pattern={{major}}.{{minor}}+acmesh${{ needs.container-pre-publish.outputs.acme-sh-version }}
        type=semver,pattern={{major}}+acmesh${{ needs.container-pre-publish.outputs.acme-sh-version }},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      ghcr-image-name: ${{ needs.container-pre-publish.outputs.container-image-name }}
      dhub-image-name: ${{ needs.container-pre-publish.outputs.container-image-name }}
      dhub-readme-file: ./CONTAINER.md
    secrets:
      dhub-username: ${{ secrets.DHUB_USERNAME }}
      dhub-password: ${{ secrets.DHUB_PASSWORD }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-password: ${{ secrets.GITHUB_TOKEN }}
