name: Validate & publish container project

on:
  schedule:
    - cron: '0 0 * * *' # nightly
  push:
    branches: [ main ] # edge
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ] # versioned

jobs:
  container-validate:
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@b67d6c1e63fb221a1d8b696dadaa379a380a01c2

  acme-dns-pre-publish:
    needs: container-validate
    uses: ./.github/workflows/acme-dns-pre-publish.yml
    with:
      build-context: src

  container-publish:
    needs: [container-validate, acme-dns-pre-publish]
    permissions:
      packages: write
      id-token: write # used to complete the identity challenge with sigstore/fulcio
    uses: anthochamp/dev-toolbox/.github/workflows/container-publish.yml@b67d6c1e63fb221a1d8b696dadaa379a380a01c2
    with:
      build-context: src
      container-tags: ${{ needs.acme-dns-pre-publish.outputs.container-tags }}
      ghcr-image-name: ${{ needs.acme-dns-pre-publish.outputs.container-image-name }}
      dhub-image-name: ${{ needs.acme-dns-pre-publish.outputs.container-image-name }}
    secrets:
      dhub-username: ${{ secrets.DHUB_USERNAME }}
      dhub-password: ${{ secrets.DHUB_PASSWORD }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-password: ${{ secrets.GITHUB_TOKEN }}

  update-docker-hub-repo-desc:
    needs: [container-validate, acme-dns-pre-publish]
    uses: anthochamp/dev-toolbox/.github/workflows/misc-docker-hub-update-repo-desc.yml@ded58a4ac9ac94a16eda4fc27761d19c2fd806df
    with:
      readme-file: ./CONTAINER.md
    secrets:
      username: ${{ secrets.DHUB_USERNAME }}
      password: ${{ secrets.DHUB_PASSWORD }}
      repository: ${{ secrets.DHUB_USERNAME }}/${{ needs.acme-dns-pre-publish.outputs.container-image-name }}
