name: Validate container project

on:
  push:
    branches: [ 'main', 'v[0-9]+', 'v[0-9]+.[0-9]+' ]
    tags-ignore: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:

jobs:
  container-validate:
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@8bc77bcb4ed6d17c0ca1218e5447b2ac9b9b6bbb
