name: Validate

on:
  push:
    branches: [ '!main', 'v[0-9]+', 'v[0-9]+.[0-9]+' ]
    tags-ignore: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:

jobs:
  validate:
    uses: anthochamp/dev-toolbox/.github/workflows/container-validate.yml@1938d42ba397297b57d082f3b557992680a80ab3
